### PR TITLE
Ambr 1020

### PR DESCRIPTION
**Pull request by egh**
https://jira.plos.org/jira/browse/AMBR-1020

Stop using plos queue. Removes any reference to solr, activemq, camel, etc.

Companion PR: https://github.com/PLOS-Formulas/rhino-formula/pull/110

I'm not sure how to test this. I built a vagrant VM for this following the instructions here https://github.com/plos/molten/blob/dev/vagrant/apps/ambra/README.md#L1 and everything seems fine.

This PR *must* be deployed together with https://github.com/PLOS-Formulas/rhino-formula/pull/110

### CODE REVIEW

**Comment by msingh05** [comment]
@egh it all looks good. I am wondering if dropping the syndication table should be part of this work?

**Comment by egh** [comment]
@msingh05 I thought about dropping that table but figured we could do it in a follow up ticket. I'm not sure if there is any useful information in there. @mcbrandt13 might know more about that table?

**Comment by mcbrandt13** [comment]
At this point we migrated all the rows in the ambra syndication table into the AA table, albeit not verbatim as they are modeled a bit differently, but I think it's safe to drop the syndication table from ambra.

**Comment by msingh05** [comment]
cool. merging this pr as we will do table drop in another ticket.

**Pull request merged**
