### PR TITLE
Work around compiler bug in Eclipse

### PR DESCRIPTION
**Pull request by egh**
Eclipse is unable to infer types in certain circumstances.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=530576
Be more explicit about types to work around this issue.

### CODE REVIEW

**Comment by sjtower** [comment]
I have reservations about modifying the code because of the limitations of a compiler. Have you tried using IntelliJ instead of Eclipse?

**Comment by egh** [comment]
@sjtower I understand your concerns, but this does not modify behavior, it just makes the types explicit. 

This bug is present in the current version of eclipse. I am happy to try intellij, but I believe that if the project is open source, we should ensure it works in as many environments as possible.

**Comment by sjtower** [comment]
We use untyped stream methods like this in a few places rhino. I would hate to have to explicitly type each one. We should discuss with the team.

**Comment by egh** [comment]
These are the only ones that cause an issue, so this is the only place that needs explicit typing.

**Comment by egh** [comment]
This is fixed in eclipse 4.8, due to be released in Sept of this year.

I'm not using Eclipse any more but if we want to support our users I believe we should merge this.

**Comment by egh** [comment]
:+1: Thanks, @randy-tano !

**Pull request merged**
